---
# number of instances to deploy
instance_total: 3

# instance name, will automatically appneded by $index
instance_name: demo

# provide SSH public key
ec2_key_pair: '{{ lookup("file","~/.ssh/id_rsa.pub") }}'

# the VPC name for all instances
ec2_vpc_name: demo

# choose an instance flavor
# for AAP the recommended value is t3.large
instance_flavor: t3.large
