---
- name: associate new elastic IPs with each of the instances
  community.aws.ec2_eip:
    device_id: "{{ item }}"
    region: "{{ ec2_region }}"
  register: elastic_ip

- name: create Route53 DNS record {{ _instance_name }}.{{ route53_domain }} with IP {{ elastic_ip.public_ip }}
  community.aws.route53:
    state: present
    zone: "{{ route53_domain }}"
    record: "{{ _instance_name }}.{{ route53_domain }}"
    type: A
    value: "{{ elastic_ip.public_ip }}"
    ttl: 600
    wait: true
    overwrite: true
