---
- name: set internal instance name
  ansible.builtin.set_fact:
    _instance_name: "{{ instance_name }}{{ item }}"

- name: create each cloud instance "{{ _instance_name }}"
  ansible.builtin.include_role:
    name: ansible_ssa.general.instance
  vars:
    instance_name: "{{ _instance_name }}"

- name: assign elastisc IP to instances
  ansible.builtin.include_tasks: assign_eip.yml
  loop: "{{ ec2.instance_ids }}"
  when:
    - type == "ec2"
    - not remove | bool


# - name: associate new elastic IPs with each of the instances
#   community.aws.ec2_eip:
#     device_id: "{{ item }}"
#     region: "{{ ec2_region }}"
#   loop: "{{ ec2.instance_ids }}"
#   when:
#     - type == "ec2"
#     - not remove | bool

# - debug:
#     var: ec2.instances[0]

# - name: create Route53 DNS record
#   community.aws.route53:
#     state: present
#     zone: "{{ route53_domain }}"
#     record: "{{ _instance_name }}.{{ route53_domain }}"
#     type: A
#     value: "{{ ec2.instances[0].public_ip_address }}"
#     ttl: 600
#     wait: true
#     overwrite: true
#   when:
#     - type == "ec2"
#     - not remove | bool
