---
- name: set internal instance name
  ansible.builtin.set_fact:
    _instance_name: "{{ instance_name }}{{ item }}"

- name: create each cloud instance "{{ _instance_name }}"
  ansible.builtin.include_role:
    name: ansible_ssa.general.instance
  vars:
    instance_name: "{{ _instance_name }}"

- name: assign elastisc IP to instances
  ansible.builtin.include_tasks: assign_eip.yml
  loop: "{{ ec2.instance_ids }}"
  when:
    - type == "ec2"
    - not remove | bool
